version: '2'
services:
  redis:
    image: redis:6.0.9-alpine
    container_name: "my_redis"
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf    
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]